version: "3"

networks:
  monitoring:

services:
  prometheus:
    image: docker00:5000/prometheus:1.0
    command:
#      - '--web.listen-address=0.0.0.0:9090'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'

    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always
    volumes:
      - /docker/volumes/monitoring/prometheus:/etc/prometheus
      - /docker/volumes/monitoring/prometheus/data:/prometheus

  grafana:
    image: docker00:5000/grafana:1.0
    ports:
      - "3000:3000"
    networks:
      - monitoring
    restart: always
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - /docker/volumes/monitoring/grafana:/var/lib/grafana