# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'apple'

    static_configs:
    - targets: ['172.30.0.110:9100']

  - job_name: 'berry101'

    static_configs:
    - targets: ['172.30.0.101:9100']

  - job_name: 'berry102'

    static_configs:
    - targets: ['172.30.0.102:9100']

  - job_name: 'berry103'

    static_configs:
    - targets: ['172.30.0.103:9100']

  - job_name: 'berry104'

    static_configs:
    - targets: ['172.30.0.104:9100']

  - job_name: 'berry105'

    static_configs:
    - targets: ['172.30.0.105:9100']

  - job_name: 'berry106'

    static_configs:
    - targets: ['172.30.0.106:9100']

  - job_name: 'berry107'

    static_configs:
    - targets: ['172.30.0.107:9100']

  - job_name: 'berry108'

    static_configs:
    - targets: ['172.30.0.108:9100']

  - job_name: 'berry109'

    static_configs:
    - targets: ['172.30.0.109:9100']

  - job_name: 'berry111'

    static_configs:
    - targets: ['172.30.0.111:9100']

  - job_name: 'berry121'

    static_configs:
    - targets: ['172.30.0.121:9100']

  - job_name: 'berry122'

    static_configs:
    - targets: ['172.30.0.122:9100']

  - job_name: 'berry123'

    static_configs:
    - targets: ['172.30.0.123:9100']

  - job_name: 'docker00'

    static_configs:
    - targets: ['172.30.0.60:9100']

  - job_name: 'docker01'

    static_configs:
    - targets: ['172.30.0.61:9100']

  - job_name: 'docker02'

    static_configs:
    - targets: ['172.30.0.62:9100']

  - job_name: 'nissvr'

    static_configs:
    - targets: ['172.30.0.81:9100']

  - job_name: 'mngsvr'

    static_configs:
    - targets: ['172.30.0.82:9100']

  - job_name: 'sossvr'

    static_configs:
    - targets: ['172.30.0.91:9100']
